### ISSUE TITLE
Create a __main__ entry point - App

### ISSUE THREAD

**Issue by WK-GiHu** [Comrane123/Dictionary#2]
@Comrane123 

Create a new file named `App.py` and copy the template below

- [x] Copy line 81 to 86
https://github.com/Comrane123/Dictionary/blob/d49094e2ce25e05e8b53b17eba54ae7906b33e07/Autocomplete.py#L81

- [x] Copy line 73 to 76
  https://github.com/Comrane123/Dictionary/blob/982631385ddca3dec654932fe686ebf9f413e145/Autocomplete.py#L73-L76

```
import tkinter as tk
# from Dictionary import AutocompleteEntry
from Autocomplete import AutocompleteEntry

class App(tk.Tk):
    def __init__(self):
        super().__init__()

        # Here goes line 81 to 86
        # Here goes line 73 to 76


if __name__ == "__main__":
    App().mainloop()
```

**Comment by WK-GiHu** [comment]
@Comrane123 

Read the [template](https://github.com/Comrane123/Dictionary/issues/2#issue-589901059) again, you are missing one line.

---

If you run `App.py` you see **two** `undefined` errors.
Do you understand such errors and know how to fix it?

After fixing the above error, runing `App.py` and the `AutocompleteEntry` should work as expected.
If not, notify me. 
If OK, continue with https://github.com/Comrane123/Dictionary/issues/5

**Comment by Comrane123** [comment]
@WK-GiHu 

Fixed it by importing `sqlite3` and swapping `root` with `self`.
