### ISSUE TITLE
What is dictionary.db?

### ISSUE THREAD

**Issue by WK-GiHu** [Comrane123/Dictionary#4]
@Comrane123 

What is `'dictionary.db'`?
https://github.com/Comrane123/Dictionary/blob/d49094e2ce25e05e8b53b17eba54ae7906b33e07/Autocomplete.py#L81

**Comment by Comrane123** [comment]
@WK-GiHu

It`s a sqlite database with English and Russian words for the dictionary
I also uploaded it
