### ISSUE TITLE
Dictionary.py

### ISSUE THREAD

**Issue by WK-GiHu** [Comrane123/Dictionary#5]
@Comrane123 

###Dictionary.py

Are the whole `class AutocompleteEntry` in `Dictionary.py` a copy from `Autocomplete.py`?

- [x] Yes, then remove it.
- [ ] No, show/tell which part you want still to use

**Comment by WK-GiHu** [comment]
@Comrane123 

### Dictionary.py

- [x] Add after line 3 `from Autocomplete import AutocompleteEntry`
https://github.com/Comrane123/Dictionary/blob/ab95ac67009c9b03947bc9d7a5c3b3cc4b932121/Dictionary.py#L3

- [x] Disable line 9, `# `, this belongs to `class AutocompleteEntry`
  As for now don't know why this may required
  https://github.com/Comrane123/Dictionary/blob/ab95ac67009c9b03947bc9d7a5c3b3cc4b932121/Dictionary.py#L9

- [x] Change line 34 according to line 18 from `App.py`
  https://github.com/Comrane123/Dictionary/blob/ab95ac67009c9b03947bc9d7a5c3b3cc4b932121/Dictionary.py#L34
  https://github.com/Comrane123/Dictionary/blob/ab95ac67009c9b03947bc9d7a5c3b3cc4b932121/App.py#L18

- [x] Copy lines 11 to 16 before line 109
  https://github.com/Comrane123/Dictionary/blob/ab95ac67009c9b03947bc9d7a5c3b3cc4b932121/App.py#L11-L16

- [x] Change line 109 back to `dictionary = Dictionary()`
https://github.com/Comrane123/Dictionary/blob/ab95ac67009c9b03947bc9d7a5c3b3cc4b932121/Dictionary.py#L109

- [x] Insert before line 110 `dictionary.word_input_entry.set_completion_list(test_list)`
  https://github.com/Comrane123/Dictionary/blob/ab95ac67009c9b03947bc9d7a5c3b3cc4b932121/Dictionary.py#L110

Give it a try ..., fix thrown errors if any.
The goal for now is to have the `AutocompleteEntry` working.

I didn't get your language selection part yet, disable it if it wont not run.
Notify me if done, report if its working as expected or tell which part is not what you want and show any errors you can't fix yourself.

**Comment by Comrane123** [comment]
@WK-GiHu 
Thanks, everything is working perfectly!

About language selection part - it has to switch between translating Eng/Rus and Rus/Eng, but that's a way simpler thing to do, so ill try to figure it out on my own.

Really appreciate your help!
